tasks:
  - name: terraform
    before: |
      source /workspace/terraform-beginner-bootcamp-2023/bin/install_terraform_cli
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source /workspace/terraform-beginner-bootcamp-2023/bin/install_aws_cli

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform