

terraform {

  required_providers {
    terratowns = {
      source = "local.providers/local/terratowns"
      version = "1.0.0"
    }
  }
}
  #backend "remote" {
  #  hostname = "app.terraform.io"
  #  organization = "ExamPro"

  #  workspaces {
  #    name = "terra-house-1"
  #  }
  #}
  #cloud {
  #  organization = "ExamPro"
  #  workspaces {
  #    name = "terra-house-1"
  #  }
  #}
provider "terratowns" {
  # endpoint = "http://localhost:4567/api"
  endpoint = var.terratowns_endpoint
  user_uuid = var.terratowns_user_uuid
  token = var.access_token
}
# }
module "terrahouse_aws" {
  source = "./modules/terrahouse_aws"
  user_uuid = var.terratowns_user_uuid
  bucket_name = var.bucket_name
  path_index_html = var.path_index_html
  path_error_html = var.path_index_html
  content_variable = var.content_variable
  assets_path = var.assets_path
}

resource "terratowns_home" "home" {
  name = "Top 10 anime quotes Generated by AI!!"
  description = <<DESCRIPTION
Anime quotes are memorable lines spoken by characters in Japanese animation, 
often encapsulating profound themes, emotions, or philosophies. 
These quotes range from inspirational and motivational to humorous and reflective,
resonating with audiences worldwide.
DESCRIPTION
  #domain_name = module.terrahouse_aws.cloudfront_url
  domain_name = module.terrahouse_aws.cloudfront_url
  town = "missingo"
  content_version = 1
}